name: FP-Next
version: 1.0.0
main: de.fantasypixel.rework.FPRework
author: zManuu
description: Fantasypixel Rework 2023-2024
api-version: 1.19
commands:
  savepoints:
  options:
    aliases:
      - settings
      - account
  item: